# Generated by Django 5.2.5 on 2025-08-07 14:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafe", "0008_bill_bill_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("table_number", models.CharField(max_length=10, unique=True)),
                ("table_name", models.CharField(blank=True, max_length=50, null=True)),
                ("capacity", models.IntegerField(default=4)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "qr_code",
                    models.ImageField(blank=True, null=True, upload_to="qr_codes/"),
                ),
                (
                    "qr_unique_id",
                    models.CharField(default=uuid.uuid4, max_length=50, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="bill",
            name="table_number",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="menu_item",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="order",
            name="estimated_time",
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name="order",
            name="special_instructions",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("preparing", "Preparing"),
                    ("ready", "Ready"),
                    ("served", "Served"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="table_unique_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
