# Generated by Django 5.2.5 on 2025-08-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafe", "0009_table_bill_table_number_menu_item_is_available_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
