# Generated by Django 5.2.5 on 2025-08-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafe", "0010_alter_table_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="visual_x",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="table",
            name="visual_y",
            field=models.IntegerField(default=0),
        ),
    ]
