# Generated by Django 5.2.5 on 2025-08-07 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cafe", "0012_floor_table_floor"),
    ]

    operations = []
