# Generated by Django 5.2.5 on 2025-08-16 15:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafe", "0014_add_table_shape_and_room"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="menu_item",
            options={"ordering": ["category", "name"]},
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RenameField(
            model_name="menu_item",
            old_name="desc",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="order_id",
            new_name="id",
        ),
        migrations.RemoveField(
            model_name="menu_item",
            name="pic",
        ),
        migrations.RemoveField(
            model_name="order",
            name="order_time",
        ),
        migrations.AddField(
            model_name="menu_item",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="fimage"),
        ),
        migrations.AddField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="order_type",
            field=models.CharField(
                choices=[("table", "Table"), ("room", "Room")],
                default="table",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="room_unique_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="menu_item",
            name="category",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="menu_item",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="menu_item",
            name="list_order",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="order",
            name="bill_clear",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="order",
            name="estimated_time",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="order",
            name="name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="order",
            name="phone",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="order",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="order",
            name="table",
            field=models.CharField(max_length=15),
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="cafe.department",
                    ),
                ),
            ],
            options={
                "ordering": ["department", "name"],
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("room_number", models.CharField(max_length=10, unique=True)),
                ("room_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("single", "Single Room"),
                            ("double", "Double Room"),
                            ("triple", "Triple Room"),
                            ("suite", "Suite"),
                            ("deluxe", "Deluxe Room"),
                            ("presidential", "Presidential Suite"),
                        ],
                        default="single",
                        max_length=20,
                    ),
                ),
                ("capacity", models.IntegerField(default=2)),
                (
                    "price_per_night",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "room_status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("occupied", "Occupied"),
                            ("maintenance", "Under Maintenance"),
                            ("reserved", "Reserved"),
                            ("cleaning", "Being Cleaned"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True, null=True, upload_to="room_qr_codes/"
                    ),
                ),
                (
                    "qr_unique_id",
                    models.CharField(default=uuid.uuid4, max_length=50, unique=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("amenities", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "floor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="cafe.floor",
                    ),
                ),
            ],
            options={
                "ordering": ["floor", "room_number"],
            },
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("employee_id", models.CharField(max_length=20, unique=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=15)),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("address", models.TextField()),
                ("emergency_contact_name", models.CharField(max_length=100)),
                ("emergency_contact_phone", models.CharField(max_length=15)),
                ("hire_date", models.DateField()),
                ("salary", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "employment_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("terminated", "Terminated"),
                            ("on_leave", "On Leave"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="staff_profiles/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff",
                        to="cafe.department",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff",
                        to="cafe.role",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["employee_id"],
            },
        ),
        migrations.CreateModel(
            name="Leave",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("annual", "Annual Leave"),
                            ("sick", "Sick Leave"),
                            ("personal", "Personal Leave"),
                            ("maternity", "Maternity Leave"),
                            ("paternity", "Paternity Leave"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_leaves",
                        to="cafe.staff",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaves",
                        to="cafe.staff",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("check_in_time", models.TimeField(blank=True, null=True)),
                ("check_out_time", models.TimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("late", "Late"),
                            ("half_day", "Half Day"),
                            ("leave", "Leave"),
                        ],
                        default="present",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="cafe.staff",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
                "unique_together": {("staff", "date")},
            },
        ),
    ]


